const abilityTranslations: Record<string, string> = {
  "adaptability": "Adaptable",
  "aerilate": "Piel Celeste",
  "aftermath": "Detonación",
  "air-lock": "Bucle Aire",
  "analytic": "Cálculo Final",
  "anger-point": "Irascible",
  "anger-shell": "Coraza Ira",
  "anticipation": "Anticipación",
  "arena-trap": "Trampa Arena",
  "armor-tail": "Cola Armadura",
  "aroma-veil": "Velo Aroma",
  "as-one-glastrier": "Unidad Ecuestre",
  "as-one-spectrier": "Unidad Ecuestre",
  "aura-break": "Rompeaura",
  "bad-dreams": "Mal Sueño",
  "ball-fetch": "Recogebolas",
  "battery": "Batería",
  "battle-armor": "Armadura Batalla",
  "battle-bond": "Fuerte Afecto",
  "beads-of-ruin": "Abalorio Debacle",
  "beast-boost": "Ultraimpulso",
  "berserk": "Cólera",
  "big-pecks": "Sacapecho",
  "blaze": "Mar Llamas",
  "bulletproof": "Antibalas",
  "cheek-pouch": "Carrillo",
  "chilling-neigh": "Relincho Blanco",
  "chlorophyll": "Clorofila",
  "clear-body": "Cuerpo Puro",
  "cloud-nine": "Aclimatación",
  "color-change": "Cambio Color",
  "comatose": "Letargo Perenne",
  "commander": "Comandar",
  "competitive": "Tenacidad",
  "compound-eyes": "Ojo Compuesto",
  "contrary": "Respondón",
  "corrosion": "Corrosión",
  "costar": "Unísono",
  "cotton-down": "Pelusa",
  "cud-chew": "Rumia",
  "curious-medicine": "Medicina Extraña",
  "cursed-body": "Cuerpo Maldito",
  "cute-charm": "Gran Encanto",
  "damp": "Humedad",
  "dancer": "Pareja de Baile",
  "dark-aura": "Aura Oscura",
  "dauntless-shield": "Escudo Recio",
  "dazzling": "Cuerpo Vívido",
  "defeatist": "Flaqueza",
  "defiant": "Competitivo",
  "delta-stream": "Ráfaga Delta",
  "desolate-land": "Tierra del Ocaso",
  "disguise": "Disfraz",
  "download": "Descarga",
  "dragonize": "Piel Dragontina",
  "dragons-maw": "Mandíbula Dragón",
  "drizzle": "Llovizna",
  "drought": "Sequía",
  "dry-skin": "Piel Seca",
  "early-bird": "Madrugar",
  "earth-eater": "Geofagia",
  "effect-spore": "Efecto Espora",
  "electric-surge": "Electrogénesis",
  "electromorphosis": "Dinamo",
  "embody-aspect": "Evocarrecuerdos",
  "emergency-exit": "Retirada",
  "fairy-aura": "Aura Feérica",
  "filter": "Filtro",
  "flame-body": "Cuerpo Llama",
  "flare-boost": "Ímpetu Ardiente",
  "flash-fire": "Absorbe Fuego",
  "flower-gift": "Don Floral",
  "flower-veil": "Velo Flor",
  "fluffy": "Peluche",
  "forecast": "Predicción",
  "forewarn": "Alerta",
  "friend-guard": "Compiescolta",
  "frisk": "Cacheo",
  "full-metal-body": "Guardia Metálica",
  "fur-coat": "Pelaje Recio",
  "gale-wings": "Alas Vendaval",
  "galvanize": "Piel Eléctrica",
  "gluttony": "Gula",
  "good-as-gold": "Cuerpo Áureo",
  "gooey": "Baba",
  "gorilla-tactics": "Monotema",
  "grass-pelt": "Manto Frondoso",
  "grassy-surge": "Herbogénesis",
  "grim-neigh": "Relincho Negro",
  "guard-dog": "Perro Guardián",
  "gulp-missile": "Tragamisil",
  "guts": "Agallas",
  "hadron-engine": "Motor Hadrónico",
  "harvest": "Cosecha",
  "healer": "Alma Cura",
  "heatproof": "Ignífugo",
  "heavy-metal": "Metal Pesado",
  "honey-gather": "Recogemiel",
  "hospitality": "Hospitalidad",
  "huge-power": "Potencia",
  "hunger-switch": "Mutapetito",
  "hustle": "Entusiasmo",
  "hydration": "Hidratación",
  "hyper-cutter": "Corte Fuerte",
  "ice-body": "Gélido",
  "ice-face": "Cara de Hielo",
  "ice-scales": "Escama de Hielo",
  "illuminate": "Iluminación",
  "illusion": "Ilusión",
  "immunity": "Inmunidad",
  "imposter": "Impostor",
  "infiltrator": "Allanamiento",
  "innards-out": "Revés",
  "inner-focus": "Fuerza Mental",
  "insomnia": "Insomnio",
  "intimidate": "Intimidación",
  "intrepid-sword": "Espada Indómita",
  "iron-barbs": "Punta Acero",
  "iron-fist": "Puño Férreo",
  "justified": "Justiciero",
  "keen-eye": "Vista Lince",
  "klutz": "Zoquete",
  "leaf-guard": "Defensa Hoja",
  "levitate": "Levitación",
  "libero": "Líbero",
  "light-metal": "Metal Liviano",
  "lightning-rod": "Pararrayos",
  "limber": "Flexibilidad",
  "lingering-aroma": "Olor Persistente",
  "liquid-ooze": "Lodo Líquido",
  "liquid-voice": "Voz Fluida",
  "long-reach": "Remoto",
  "magic-bounce": "Espejo Mágico",
  "magic-guard": "Muro Mágico",
  "magician": "Prestidigitador",
  "magma-armor": "Escudo Magma",
  "magnet-pull": "Imán",
  "marvel-scale": "Escama Especial",
  "mega-launcher": "Megadisparador",
  "mega-sol": "Megasolar",
  "merciless": "Ensañamiento",
  "mimicry": "Mimetismo",
  "minds-eye": "Ojo Mental",
  "minus": "Menos",
  "mirror-armor": "Coraza Reflejo",
  "misty-surge": "Nebulogénesis",
  "mold-breaker": "Rompemoldes",
  "moody": "Veleta",
  "motor-drive": "Electromotor",
  "moxie": "Autoestima",
  "multiscale": "Multiescamas",
  "multitype": "Multitipo",
  "mummy": "Momia",
  "mycelium-might": "Poder Fúngico",
  "natural-cure": "Cura Natural",
  "neuroforce": "Fuerza Cerebral",
  "neutralizing-gas": "Gas Reactivo",
  "no-guard": "Indefenso",
  "normalize": "Normalidad",
  "oblivious": "Despiste",
  "opportunist": "Oportunista",
  "orichalcum-pulse": "Latido Oricalco",
  "overcoat": "Funda",
  "overgrow": "Espesura",
  "own-tempo": "Ritmo Propio",
  "parental-bond": "Amor Filial",
  "pastel-veil": "Velo Pastel",
  "perish-body": "Cuerpo Mortal",
  "pickpocket": "Hurto",
  "pickup": "Recogida",
  "piercing-drill": "Turbotaladro",
  "pixilate": "Piel Feérica",
  "plus": "Más",
  "poison-heal": "Antídoto",
  "poison-point": "Punto Tóxico",
  "poison-puppeteer": "Títere Tóxico",
  "poison-touch": "Toque Tóxico",
  "power-construct": "Agrupamiento",
  "power-of-alchemy": "Reacción Química",
  "power-spot": "Fuente Energía",
  "prankster": "Bromista",
  "pressure": "Presión",
  "primordial-sea": "Mar del Albor",
  "prism-armor": "Armadura Prisma",
  "propeller-tail": "Hélice Caudal",
  "protean": "Mutatipo",
  "protosynthesis": "Paleosíntesis",
  "psychic-surge": "Psicogénesis",
  "punk-rock": "Punk Rock",
  "pure-power": "Energía Pura",
  "purifying-salt": "Sal Purificadora",
  "quark-drive": "Carga Cuark",
  "queenly-majesty": "Regia Presencia",
  "quick-draw": "Mano Rápida",
  "quick-feet": "Pies Rápidos",
  "rain-dish": "Cura Lluvia",
  "rattled": "Cobardía",
  "receiver": "Receptor",
  "reckless": "Audaz",
  "refrigerate": "Piel Helada",
  "regenerator": "Regeneración",
  "ripen": "Maduración",
  "rivalry": "Rivalidad",
  "rks-system": "Sistema Alfa",
  "rock-head": "Cabeza Roca",
  "rocky-payload": "Transportarrocas",
  "rough-skin": "Piel Tosca",
  "run-away": "Fuga",
  "sand-force": "Poder Arena",
  "sand-rush": "Ímpetu Arena",
  "sand-spit": "Expulsarena",
  "sand-stream": "Chorro Arena",
  "sand-veil": "Velo Arena",
  "sap-sipper": "Herbívoro",
  "schooling": "Banco",
  "scrappy": "Intrépido",
  "screen-cleaner": "Antibarrera",
  "seed-sower": "Disemillar",
  "serene-grace": "Dicha",
  "shadow-shield": "Guardia Espectro",
  "shadow-tag": "Sombra Trampa",
  "sharpness": "Cortante",
  "shed-skin": "Mudar",
  "sheer-force": "Potencia Bruta",
  "shell-armor": "Caparazón",
  "shield-dust": "Polvo Escudo",
  "shields-down": "Escudo Limitado",
  "simple": "Simple",
  "skill-link": "Encadenado",
  "slow-start": "Inicio Lento",
  "slush-rush": "Quitanieves",
  "sniper": "Francotirador",
  "snow-cloak": "Manto Níveo",
  "snow-warning": "Nevada",
  "solar-power": "Poder Solar",
  "solid-rock": "Roca Sólida",
  "soul-heart": "Coránima",
  "soundproof": "Insonorizar",
  "speed-boost": "Impulso",
  "spicy-spray": "Salpicante",
  "stakeout": "Vigilante",
  "stall": "Rezagado",
  "stalwart": "Acérrimo",
  "stamina": "Firmeza",
  "stance-change": "Cambio Táctico",
  "static": "Electricidad Estática",
  "steadfast": "Impasible",
  "steam-engine": "Combustible",
  "steelworker": "Acero Templado",
  "steely-spirit": "Alma Acerada",
  "stench": "Hedor",
  "sticky-hold": "Viscosidad",
  "storm-drain": "Colector",
  "strong-jaw": "Mandíbula Fuerte",
  "sturdy": "Robustez",
  "suction-cups": "Ventosas",
  "super-luck": "Afortunado",
  "supersweet-syrup": "Néctar Dulce",
  "supreme-overlord": "General Supremo",
  "surge-surfer": "Cola Surf",
  "swarm": "Enjambre",
  "sweet-veil": "Velo Dulce",
  "swift-swim": "Nado Rápido",
  "sword-of-ruin": "Espada Debacle",
  "symbiosis": "Simbiosis",
  "synchronize": "Sincronía",
  "tablets-of-ruin": "Tablilla Debacle",
  "tangled-feet": "Tumbos",
  "tangling-hair": "Rizos Rebeldes",
  "technician": "Experto",
  "telepathy": "Telepatía",
  "tera-shell": "Teracaparazón",
  "tera-shift": "Teracambio",
  "teraform-zero": "Teraformación 0",
  "teravolt": "Terravoltaje",
  "thermal-exchange": "Termoconversión",
  "thick-fat": "Sebo",
  "tinted-lens": "Cromolente",
  "torrent": "Torrente",
  "tough-claws": "Garra Dura",
  "toxic-boost": "Ímpetu Tóxico",
  "toxic-chain": "Cadena Tóxica",
  "toxic-debris": "Capa Tóxica",
  "trace": "Calco",
  "transistor": "Transistor",
  "triage": "Primer Auxilio",
  "truant": "Ausente",
  "turboblaze": "Turbollama",
  "unaware": "Ignorante",
  "unburden": "Liviano",
  "unnerve": "Nerviosismo",
  "unseen-fist": "Puño Invisible",
  "vessel-of-ruin": "Caldero Debacle",
  "victory-star": "Tinovictoria",
  "vital-spirit": "Espíritu Vital",
  "volt-absorb": "Absorbe Electricidad",
  "wandering-spirit": "Alma Errante",
  "water-absorb": "Absorbe Agua",
  "water-bubble": "Pompa",
  "water-compaction": "Hidrorrefuerzo",
  "water-veil": "Velo Agua",
  "weak-armor": "Armadura Frágil",
  "well-baked-body": "Cuerpo Horneado",
  "white-smoke": "Humo Blanco",
  "wimp-out": "Huida",
  "wind-power": "Energía Eólica",
  "wind-rider": "Surcavientos",
  "wonder-guard": "Superguarda",
  "wonder-skin": "Piel Milagro",
  "zen-mode": "Modo Daruma",
  "zero-to-hero": "Cambio Heroico",
}

export function getAbilityName(name: string): string {
  return abilityTranslations[name] ?? name
}
